enterprise:
  CreatedBy: 132016
  UpdatedBy: 10
  address_json: null
  admin_user_id: 132016
  architectureDiagram: null
  architectureInformation: null
  attachment: null
  auditComments: null
  auditStatus: APPROVED
  b2bPartner_enterprise_id: 124012
  bankCode: null
  bank_name: null
  bank_type: null
  businessLicense_code: null
  business_begin_at: null
  business_end_at: null
  business_identity: null
  business_license: '{"files":[{"name":"微信截图_20230703102935.png","url":"//lcscm-trantor-test.oss-cn-shenzhen.aliyuncs.com/images/bf346833-b17e-4452-8cff-15600b90362e.png"}]}'
  business_scope: null
  business_status: null
  card_no: null
  certificateRepresentative: null
  certification_message_id: 82008
  city_id: null
  code: CO20230703000001
  company_type: P
  contactAddress: null
  contactDepart: null
  contactEmail: 123@143.com
  contactName: 李四测试
  contactPhone: '18178952878'
  contactPosition: null
  corporate_company_id: null
  country: China
  createdAt: 2023-07-03 17:52:31
  credentials: null
  credentials_type: null
  creditReport: null
  creditReportDate: null
  currency: null
  data_source: LC
  deletedAt: 0
  detail: null
  display_expand_type: null
  district_id: null
  editType: P
  electronicSignatureAttorney: '{"files":[]}'
  enterprise_brand_distribute_relation_id: null
  enterprise_expand_id: 94005
  enterprise_type: null
  expandAuditComments: null
  expandAuditStatus: null
  factory_address_id: null
  financialStatements: null
  found: null
  grade: D
  graphicSeal: '{"files":[]}'
  id: 138013
  idRelationUnit: 0
  introduction: null
  invoiceMaxQuota: null
  isCorporateCompany: 0
  isDeleted: 0
  isManualEdit: 1
  isMonopolyUnit: 0
  legalPerson: null
  legalPosition: null
  legal_representative_contact: null
  legal_representative_id: null
  legal_representative_name: 李四测试
  longTerm: null
  name: 湖北家家有限公司
  name_used_before: null
  out_code: null
  parent_enterprise_id: null
  parent_id: null
  phone: '18178952878'
  powerAttorney: null
  price_validity_begin_at: 2023-07-01 00:00:00
  price_validity_end_at: 2031-07-01 23:59:59
  province_id: null
  qualificationCertificate: null
  rater: 谢维
  raterUser: 10
  register_code: null
  registered_capital: null
  registrationInformation: 武汉市东湖开发区超时空大楼
  registrationTaxAccess: null
  riskLevel: ULTRA_HIGH_RISK
  riskScore: 0
  risk_time: null
  short_name: null
  source: null
  street: null
  synStatus: null
  tax_payer_type: null
  taxpayer: null
  taxpayer_code: null
  three_cert_to_one: null
  type: null
  type_code: null
  unified_social_credit_code: '914200001776058818'
  updatedAt: 2024-03-20 16:59:33
  use_platform_oms: null
  use_platform_tms: null
  use_platform_wms: null
  website: '11'
