projects:
- ContractProjectList: null
  ContractProjectListCrm: null
  CreatedBy: 132016
  UpdatedBy: 10
  address: '{"address":[{"id":"110000","name":"北京"},{"id":"110100","name":"北京市"},{"id":"110102","name":"西城区"}],"city":{"$ref":"$.address[1]"},"detail":"社呵呵急急急1","province":{"$ref":"$.address[0]"},"region":{"$ref":"$.address[2]"}}'
  code: ZH20230703000010
  corporate_company: 108009
  createdAt: 2023-07-03 18:03:09
  crm_ispreperformance: null
  crm_project_id: null
  crm_project_leader_id: null
  crm_project_leader_name: null
  crm_state_code: null
  customer_payment_cycle: 30
  defaultCreateType: DEFAULT_CREATE_ENTERPRICE
  deletedAt: 0
  id: 100022
  invoice_email: null
  invoice_remark: 34567890-fghjkliuyfghjkoiuytru就哈哈哈哈哈哈打电话交换机发如何更好哈规划哈哈哈
  isAvailable: 1
  isDeleted: 0
  lc_name: ''
  name: 默认项目-湖北家家有限公司
  payment_request: 1
  performance_project_status: DISCLOSED
  purchaser_id: 138013
  remark: null
  settlement_status: null
  source: DEFAULT_CREATE
  status: ENABLED
  updatedAt: 2024-02-20 17:28:42
- ContractProjectList: 226027
  ContractProjectListCrm: null
  CreatedBy: 132016
  UpdatedBy: 10
  address: '{"address":[{"id":"110000","name":"北京"},{"id":"110100","name":"北京市"},{"id":"110102","name":"西城区"}],"city":{"$ref":"$.address[1]"},"detail":"1111111111111","province":{"$ref":"$.address[0]"},"region":{"$ref":"$.address[2]"}}'
  code: ZH20230704000001
  corporate_company: 108009
  createdAt: 2023-07-04 09:49:17
  crm_ispreperformance: null
  crm_project_id: null
  crm_project_leader_id: null
  crm_project_leader_name: null
  crm_state_code: null
  customer_payment_cycle: 30
  defaultCreateType: NOT_DEFAULT
  deletedAt: 0
  id: 100023
  invoice_email: null
  invoice_remark: '444444444444444444444444444444444444444444444444444'
  isAvailable: 1
  isDeleted: 0
  lc_name: lcCOBSCMMD20240131000020
  name: test1采购项目
  payment_request: 1
  performance_project_status: DISCLOSED
  purchaser_id: 138013
  remark: null
  settlement_status: null
  source: PURCHASER
  status: ENABLED
  updatedAt: 2024-03-26 15:42:01
- ContractProjectList: null
  ContractProjectListCrm: null
  CreatedBy: 132016
  UpdatedBy: 2001
  address: '{"address":[{"id":"420000","name":"湖北省"},{"id":"420100","name":"武汉市"},{"id":"420102","name":"江岸区"}],"city":{"$ref":"$.address[1]"},"detail":"呵呵呵呵1号","province":{"$ref":"$.address[0]"},"region":{"$ref":"$.address[2]"}}'
  code: ZH20230710000002
  corporate_company: 110002
  createdAt: 2023-07-10 11:49:06
  crm_ispreperformance: null
  crm_project_id: null
  crm_project_leader_id: null
  crm_project_leader_name: null
  crm_state_code: null
  customer_payment_cycle: 30
  defaultCreateType: NOT_DEFAULT
  deletedAt: 0
  id: 102004
  invoice_email: null
  invoice_remark: null
  isAvailable: 1
  isDeleted: 0
  lc_name: 领潮项目名称就是领潮项目名称啊
  name: 武汉的项目
  payment_request: 1
  performance_project_status: DISCLOSED
  purchaser_id: 138013
  remark: null
  settlement_status: null
  source: PURCHASER
  status: ENABLED
  updatedAt: 2024-03-20 15:31:50
- ContractProjectList: null
  ContractProjectListCrm: null
  CreatedBy: 132016
  UpdatedBy: 10
  address: '{"address":[{"id":"420000","name":"湖北省"},{"id":"420100","name":"武汉市"},{"id":"420106","name":"武昌区"}],"city":{"$ref":"$.address[1]"},"detail":"****街道***号","province":{"$ref":"$.address[0]"},"region":{"$ref":"$.address[2]"}}'
  code: ZH20231219000001
  corporate_company: 108009
  createdAt: 2023-12-19 09:27:18
  crm_ispreperformance: null
  crm_project_id: null
  crm_project_leader_id: null
  crm_project_leader_name: null
  crm_state_code: null
  customer_payment_cycle: 30
  defaultCreateType: NOT_DEFAULT
  deletedAt: 0
  id: 182003
  invoice_email: null
  invoice_remark: null
  isAvailable: 1
  isDeleted: 0
  lc_name: ''
  name: 湖北家家公司-合同测试项目
  payment_request: 1
  performance_project_status: DISCLOSED
  purchaser_id: 138013
  remark: null
  settlement_status: null
  source: PURCHASER
  status: ENABLED
  updatedAt: 2024-03-20 15:30:36
- ContractProjectList: 212019
  ContractProjectListCrm: null
  CreatedBy: 110067
  UpdatedBy: 110067
  address: '{"address":[{"id":"110000","name":"北京"},{"id":"110100","name":"北京市"},{"id":"110101","name":"东城区"}],"city":{"$ref":"$.address[1]"},"detail":"天安门","province":{"$ref":"$.address[0]"},"region":{"$ref":"$.address[2]"}}'
  code: XM202312250002
  corporate_company: 108009
  createdAt: 2023-12-25 11:15:13
  crm_ispreperformance: 0
  crm_project_id: 7eeb4bbd-351e-4252-b31b-15c83bf9bed4
  crm_project_leader_id: b99ad701-359e-ee11-be37-0017fa02a2ad
  crm_project_leader_name: 孙雪
  crm_state_code: 0
  customer_payment_cycle: 30
  defaultCreateType: NOT_DEFAULT
  deletedAt: 0
  id: 182043
  invoice_email: null
  invoice_remark: null
  isAvailable: 1
  isDeleted: 0
  lc_name: '11'
  name: 武汉市#湖北家家-测试1225#
  payment_request: 1
  performance_project_status: PERFORMANCE
  purchaser_id: 138013
  remark: null
  settlement_status: null
  source: CRM
  status: ENABLED
  updatedAt: 2024-03-20 15:29:45
- ContractProjectList: null
  ContractProjectListCrm: null
  CreatedBy: 132016
  UpdatedBy: 10
  address: '{"address":[{"id":"120000","name":"天津"},{"id":"120100","name":"天津市"},{"id":"120101","name":"和平区"}],"city":{"$ref":"$.address[1]"},"detail":"3333","province":{"$ref":"$.address[0]"},"region":{"$ref":"$.address[2]"}}'
  code: ZH20240112000002
  corporate_company: 180001
  createdAt: 2024-01-12 11:20:15
  crm_ispreperformance: null
  crm_project_id: null
  crm_project_leader_id: null
  crm_project_leader_name: null
  crm_state_code: null
  customer_payment_cycle: 30
  defaultCreateType: NOT_DEFAULT
  deletedAt: 0
  id: 196002
  invoice_email: null
  invoice_remark: null
  isAvailable: 1
  isDeleted: 0
  lc_name: '11123'
  name: 无发票信息项目
  payment_request: 1
  performance_project_status: DISCLOSED
  purchaser_id: 138013
  remark: null
  settlement_status: null
  source: PURCHASER
  status: ENABLED
  updatedAt: 2024-01-24 14:51:25
