purse_contract:
- CreatedBy: 10
  UpdatedBy: 132030
  accessories: '{"files":[{"name":"0476.jpg_wh1200.jpg","type":"jpg","url":"//lcscm-trantor-test.oss-cn-shenzhen.aliyuncs.com/trantor/attachments/033a8dd1-0807-496a-9310-42b97f253302.jpg"}]}'
  adjust_agreement: 10%
  ask_price_code: null
  ask_price_id: null
  attachment: null
  attachment_letter: '{}'
  attachments: null
  attn: 10
  audit_date: null
  authorized_person: 'NO'
  authorized_representative: ''
  belong_to_contractCode: null
  can_renew: 0
  category: 4839
  classification: null
  code: f0cdc16c581d1
  contractFileAttachment: null
  contract_amount_excluding_tax: !!python/object/apply:decimal.Decimal
  - '990099.01'
  contract_data_type: PROJECT_CONTRACT
  contract_label: null
  contract_lock_type: GET_GOODS_ORDER
  contract_option: OFFLINE
  contract_sign_option: OFFLINE_SIGN
  contract_tax: !!python/object/apply:decimal.Decimal
  - '9900.99'
  contract_tax_rate: 1
  contract_template_file_type: 7799E892-4EF4-4DDC-9416-4B0A8DA1DBDB
  contract_template_file_type_id: null
  contract_template_id: null
  contract_total_amount: !!python/object/apply:decimal.Decimal
  - '1000000.00'
  contract_type: PURCHASE_CONTRACT
  contract_type_attribute: ENGINEERING
  copy_sign_common_status: TO_BE_SUBMITTED
  corporateCompany: null
  corporateCompany_name: null
  createdAt: 2023-09-21 09:31:15
  crm_entity_id: null
  defaultCreateType: NOT_DEFAULT
  deletedAt: null
  delivery_approve: 1
  deposit_id: null
  dynamic_detail_form_view: null
  dynamic_detail_view: null
  dynamic_model_list: null
  dynamic_view: null
  end_date: 2024-09-30 23:59:59
  extra: null
  finance_attn: null
  finance_sys_code: null
  finished_path: null
  first_effective_date: 2023-09-21 09:31:15
  framework_agreement: null
  generated: null
  guarantee_agreement: 10%
  guarantee_cycle: '0'
  id: 158001
  instance_id: null
  internal_accessories: null
  isAvailable: 1
  isDeleted: 0
  is_contract_additional_costs: 0
  is_framework_agreement: 'NO'
  is_nonstandard: 'YES'
  is_oa_option: 1
  is_online_push_oa: 0
  is_place_on_file: null
  is_push_Oa: 0
  is_remind: 'OFF'
  is_standard_terms: null
  is_supplementary_agreement: null
  is_translation: 0
  key_words: 立邦
  last_update: 2001
  letter_of_guarantee_id: null
  max_bill_period: 2
  mobile: ''
  name: 哈哈-立邦-合同01号
  oa_call_back_status: null
  oa_status: OA_SUCCESS
  overdue_status: UNEXPIRED
  parta: 1000001
  parta_contact_email: 123@111.com
  parta_contact_mobile: '18178952878'
  parta_contact_name: test1
  parta_name: 深圳领潮供应链管理有限公司
  partb: 138017
  partb_contact_email: 123@111.com
  partb_contact_mobile: '18178952877'
  partb_contact_name: test2
  partb_name: 深圳哈哈有限公司
  party_editable: 1
  pay_type: '["CASH"]'
  payment_group: 44001
  payment_group_name: test合同专用_f0cdc16c581d1
  payment_template_id: null
  performance_price: null
  price: null
  project: null
  protocol_code: null
  protocol_name: null
  push_gateway_date: 2023-09-21 09:31:15
  quotation_id: null
  remark: null
  renewal_method: ORIGINAL
  sales_sign_file: null
  sequence_no: null
  sign_at: null
  sign_attachment: null
  sign_code: null
  sign_common_status: TO_BE_SUBMITTED
  sign_date: 2023-09-21 00:00:00
  sign_file: null
  sign_status: null
  signed_path: null
  sourcing_info_code: null
  sourcing_supplier_info_code: null
  start_date: 2023-09-21 00:00:00
  status: ENABLE
  supply_cycle: '7'
  sync_status: TO_BE_PUSHED
  system: SRM
  template: 0
  to_be_update_contract: null
  type: PURCHASE_CONTRACT
  unloading_agreement: 10%
  updatedAt: 2024-03-18 15:32:22
  year_interest_rate: !!python/object/apply:decimal.Decimal
  - '3.00'
  zj_code: null
  zj_name: null
