supplier_enterprse:
- CreatedBy: 132030
  UpdatedBy: 116015
  address_json: null
  admin_user_id: 132030
  architectureDiagram: null
  architectureInformation: null
  attachment: null
  auditComments: null
  auditStatus: APPROVED
  b2bPartner_enterprise_id: 124016
  bankCode: null
  bank_name: 深圳市龙华区龙华人民路建设银行
  bank_type: 建设银行
  businessLicense_code: null
  business_begin_at: null
  business_end_at: null
  business_identity: null
  business_license: '{"files":[{"name":"微信截图_20230703102935.png","url":"//lcscm-trantor-test.oss-cn-shenzhen.aliyuncs.com/images/56e52e70-f3c1-41da-9a9c-ae7f05523402.png"},{"name":"微信截图_20230703102935.png","type":"png","url":"//lcscm-trantor-test.oss-cn-shenzhen.aliyuncs.com/trantor/attachments/78ef8167-a8b9-4fcf-87ad-9f5e30f865a2.png"}]}'
  business_scope: null
  business_status: null
  card_no: '63221877998765353331'
  certificateRepresentative: null
  certification_message_id: 82010
  city_id: null
  code: CO20230705000002
  company_type: PSD
  contactAddress: 深圳市龙华区龙华人民路8888号
  contactDepart: null
  contactEmail: 123@153.com
  contactName: 熊晨曦
  contactPhone: '18178952877'
  contactPosition: null
  corporate_company_id: null
  country: China
  createdAt: 2023-07-05 15:01:53
  credentials: null
  credentials_type: null
  creditReport: null
  creditReportDate: null
  currency: null
  data_source: LC
  deletedAt: 0
  detail: null
  display_expand_type: null
  district_id: null
  editType: S
  electronicSignatureAttorney: null
  enterprise_brand_distribute_relation_id: null
  enterprise_expand_id: 94007
  enterprise_type: D
  expandAuditComments: null
  expandAuditStatus: null
  factory_address_id: null
  financialStatements: null
  found: null
  grade: null
  graphicSeal: '{"files":[{"name":"微信截图_20230703102935.png","type":"png","url":"//lcscm-trantor-test.oss-cn-shenzhen.aliyuncs.com/trantor/attachments/3fdbc0df-ff24-4e1b-bf92-d2991c85446b.png"}]}'
  id: 138017
  idRelationUnit: 0
  introduction: null
  invoiceMaxQuota: null
  isCorporateCompany: 0
  isDeleted: 0
  isManualEdit: 0
  isMonopolyUnit: 0
  legalPerson: null
  legalPosition: null
  legal_representative_contact: null
  legal_representative_id: null
  legal_representative_name: 熊晨曦
  longTerm: null
  name: 深圳哈哈有限公司
  name_used_before: null
  out_code: null
  parent_enterprise_id: null
  parent_id: null
  phone: '18178952877'
  powerAttorney: null
  price_validity_begin_at: 2023-07-05 00:00:00
  price_validity_end_at: 2029-07-13 23:59:59
  province_id: null
  qualificationCertificate: null
  rater: null
  raterUser: null
  register_code: null
  registered_capital: null
  registrationInformation: 深圳市龙华区龙华人民路8888号
  registrationTaxAccess: null
  riskLevel: null
  riskScore: null
  risk_time: null
  short_name: null
  source: null
  street: null
  synStatus: null
  tax_payer_type: null
  taxpayer: null
  taxpayer_code: null
  three_cert_to_one: null
  type: null
  type_code: null
  unified_social_credit_code: 9144010173971356XX
  updatedAt: 2024-03-21 19:59:45
  use_platform_oms: null
  use_platform_tms: null
  use_platform_wms: null
  website: '11'
